# Generated by Django 4.1.2 on 2022-11-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_remove_photos_comments_remove_post_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(null=True, upload_to="photos/%Y/%m/%d/"),
        ),
    ]
