# Generated by Django 4.1.2 on 2022-11-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_alter_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="points",
            name="post_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.post",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="user_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="userprofile.user",
            ),
            preserve_default=False,
        ),
    ]
