# Generated by Django 4.1.2 on 2022-11-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0004_points_post_id_post_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="comments",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="photos",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="points",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="points",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user_id",
            new_name="user",
        ),
    ]
